stages:
  - test
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

.mvn_job:
  image:
    name: maven:3.9.16-eclipse-temurin-17
    pull_policy: if-not-present
  cache:
    key: maven
    paths:
      - .m2/repository/

test:
  extends: .mvn_job
  stage: test
  script:
    - mvn test
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"'

build:
  extends: .mvn_job
  stage: build
  script:
    - mvn install
  artifacts:
    paths:
      - target/*.jar
  only:
    refs:
      - main

build-image:
  image:
    name: docker:27-cli
    pull_policy: if-not-present
  needs:
    - job: build
      artifacts: true
  stage: build
  script:
    - CI_IMAGE_NAME="${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG:-latest}"
    - echo $CI_IMAGE_NAME
    - DOCKERHUB_IMAGE_NAME="$DOCKERHUB_USER/$CI_PROJECT_NAME:${CI_COMMIT_TAG:-latest}"
    - echo $DOCKERHUB_IMAGE_NAME
    - docker build -t $CI_IMAGE_NAME -t $DOCKERHUB_IMAGE_NAME .
    - docker login "${CI_REGISTRY}" -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
    - docker push $CI_IMAGE_NAME
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
    - docker push $DOCKERHUB_IMAGE_NAME
  only:
    refs:
      - main

deploy:
  image:
    name: dtzar/helm-kubectl:4.3.0
    pull_policy: if-not-present
  stage: deploy
  script:
    - mkdir ~/.kube
    - echo ${KUBE_CONFIG} | base64 -d > ~/.kube/config
    - helm upgrade simpleapp ./helm --set image.tag="${CI_COMMIT_TAG:-latest}"
    - kubectl rollout restart deployment/simpleapp
  only:
    refs:
      - main
